config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#index"
  resources :dishes
  resources :meals 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
end

app/models/meal.rb
class Meal < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def new
    @meal = Meal.new
  end

  def create
    meal = Meal.new(meal_params)
    if meal.save
      redirect_to root_path
    else
      redirect_to new_meal_path
    end
  end

  private

  def meal_params
    params.require(:meal).permit(:name, :price, :restaurant, :city)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def new
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/dishes/create.html.erb
<h1>Dishes#create</h1>
<p>Find me in app/views/dishes/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodbook</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-default">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <a class="navbar-brand" href="<%= root_path %>">Brand</a>
      <ul class="nav navbar-nav navbar-right">
            <li><a href="<%= new_dish_path %>">New Dish</a></li>
            <li><a href="<%= new_meal_path %>">New meal</a></li>
      </ul>

     </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/meals/create.html.erb
<h1>Meals#create</h1>
<p>Find me in app/views/meals/create.html.erb</p>

app/views/meals/new.html.erb
<div class="container">
  <%= form_for @meal do |f| %>
    <div class="from-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="from-group">
      <%= f.label :price %>
      <%= f.number_field :price, class: "form-control" %>
    </div>
    <div class="from-group">
      <%= f.label :restaurant %>
      <%= f.text_field :restaurant, class: 'form-control' %>
    </div>
    <div class="from-group">
      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>
    </div>

      <%= f.submit "Crea", class: "btn btn-primary" , style: "margin-top:20px;"%>

  <% end %>

</div>

app/views/static_pages/index.html.erb
<h1 class="text-center" > WELCOME TO FOOD BOOK</h1>
<div class="container">
<section class="chirps">
  
</section>
</div>